MP1:
  image: eclipse-temurin:17
  script:
    - cd MP1
    - ./gradlew test
  artifacts:
    paths:
      - MP1/build/reports
    when: always
    expire_in: 1 day
  rules:
    - changes:
      - MP1/**/*
